stages:    
  - develop

develop-job:    
  stage: develop
  only:
    - develop

  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$id_rsa" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
   - ssh ubuntu@"$server" "$deploy"
